<?php

/**
 * @file
 * A module for testing making node base fields' displays configurable.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\book_display_configurable_test\Hook\BookDisplayConfigurableTestHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
#[LegacyHook]
function book_display_configurable_test_entity_base_field_info_alter($base_field_definitions, EntityTypeInterface $entity_type): void {
  \Drupal::service(BookDisplayConfigurableTestHooks::class)->entityBaseFieldInfoAlter($base_field_definitions, $entity_type);
}

/**
 * Implements hook_entity_type_build().
 */
#[LegacyHook]
function book_display_configurable_test_entity_type_build(array $entity_types): void {
  \Drupal::service(BookDisplayConfigurableTestHooks::class)->entityTypeBuild($entity_types);
}
