<?php

/**
 * Implements hook_theme().
 */

function techbrushup_core_theme($existing, $type, $theme, $path)
{
    return [
        "topbar" => [
            "variables" => [
                'user_picture_url' => NULL,
            ],
        ],
        "header" => [
            "variables" => [
                'user_picture_url' => NULL,
            ],
        ],        
        "footer" => [
            "variables" => [
                "body_text" => null,
                "body_text" => null,
            ],
        ],
    ];
}


function techbrushup_core_update_9001() {

  $entity_type_manager = \Drupal::entityTypeManager();
  $entity_type_manager->clearCachedDefinitions();

  $entity_type_ids = [];
  $change_summary = \Drupal::service('entity.definition_update_manager')->getChangeSummary();
  foreach ($change_summary as $entity_type_id => $change_list) {
    $entity_type = $entity_type_manager->getDefinition($entity_type_id);
    \Drupal::entityDefinitionUpdateManager()->installEntityType($entity_type);
    $entity_type_ids[] = $entity_type_id;
  }

  return t("Installed/Updated the entity type(s): @entity_type_ids", [
    '@entity_type_ids' => implode(', ', $entity_type_ids),
  ]);
}